// Macovei Nicolae-Cristian
// Anul I, grupa 312CAb

#define CMD_BUFFER_SIZE 1000

#define IMAGE_GRAYSCALE 0
#define IMAGE_COLOR 1
#define IMAGE_BLACK_WHITE 2

#define APPLY_PARAM_NON_EXISTENT -1
#define APPLY_PARAM_BAD 0
#define APPLY_PARAM_EDGE 1
#define APPLY_PARAM_SHARPEN 2
#define APPLY_PARAM_BLUR 3
#define APPLY_PARAM_GAUSSIAN_BLUR 4
