#define CMD_BUFFER_SIZE 1000

#define IMAGE_TYPE_PPM 1
#define IMAGE_TYPE_PGM 0

#define APPLY_PARAM_BAD 0
#define APPLY_PARAM_EDGE 1
#define APPLY_PARAM_SHARPEN 2
#define APPLY_PARAM_BLUR 3
#define APPLY_PARAM_GAUSSIAN_BLUR 4